[package]
name = "rustorm"
version = "0.1.0"
edition = "2021"
description = "Entity Framework-style ORM in pure Rust using PostgreSQL TCP"
license = "MIT"
authors = ["Your Name <your@email.com>"]

[dependencies]
postgres = "0.19"
thiserror = "1.0"
